/*
    This file has been autogenerated using [generate_version_header.py].
    This file may be overwritten.
*/
#ifndef _VERSION_HPP_
#define _VERSION_HPP_

static const char* VERSION = "d07efeb1";

#endif

